### ISSUE TITLE
Can't install any of the blake3 packages via npm

### ISSUE THREAD

**Issue by forbjok** [connor4312/blake3#50]
If I try to install the blake3 npm package with `npm i blake3`, I just get this error message:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for blake3-wasm@2.1.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

If I instead try `npm i blake3-wasm`, I instead get:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @c4312/blake3-internal@2.1.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I don't know why it's trying to install version 2.1.7 of the dependencies, when as far as I can tell the latest versions of all of these packages on npm is 3.0.0, but in any case it doesn't work and I seemingly have no way to be able to use these at the moment.

Is there some way to actually install these?

**Comment by SankaD** [comment]
![image](https://user-images.githubusercontent.com/2997480/198169708-43558091-c562-4cb4-a6ce-0a42adb694c3.png)

I think this is the cause.

**Comment by vans163** [comment]
```
35 http fetch GET 200 https://registry.npmjs.org/blake3-wasm 21ms (cache hit)
36 silly placeDep ROOT blake3-wasm@3.0.0 OK for:  want: v3.0.0
37 silly fetch manifest @c4312/blake3-internal@2.1.7
38 http fetch GET 200 https://registry.npmjs.org/@c4312%2fblake3-internal 9ms (cache hit)
39 timing idealTree:#root Completed in 40ms
40 silly placeDep node_modules/blake3-wasm @c4312/blake3-internal@ OK for: blake3-wasm@3.0.0 want: 2.1.7
41 timing idealTree:node_modules/blake3-wasm Completed in 3ms
42 timing idealTree:node_modules/blake3-wasm/node_modules/@c4312/blake3-internal Completed in 0ms
43 timing idealTree:buildDeps Completed in 43ms
44 timing idealTree:fixDepFlags Completed in 0ms
45 timing idealTree Completed in 59ms
46 timing command:install Completed in 77ms
47 verbose type version
48 verbose stack @c4312/blake3-internal: No matching version found for @c4312/blake3-internal@2.1.7.
48 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
48 verbose stack     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:126:26
48 verbose stack     at async Promise.all (index 0)
48 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1066:5)
48 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
48 verbose stack     at async Promise.all (index 1)
48 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
48 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:159:5)
48 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:66:5)
49 verbose cwd /tmp
50 verbose Linux 5.15.0-48-generic
51 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "blake3-wasm@v3.0.0"
52 verbose node v17.9.0
53 verbose npm  v8.5.5
54 error code ETARGET
55 error notarget No matching version found for @c4312/blake3-internal@2.1.7.
56 error notarget In most cases you or one of your dependencies are requesting
56 error notarget a package version that doesn't exist.
57 verbose exit 1
58 timing npm Completed in 301ms
59 verbose unfinished npm timer reify 1666901095273
60 verbose unfinished npm timer reify:loadTrees 1666901095289
61 verbose code 1
62 error A complete log of this run can be found in:
62 error     /home/user/.npm/_logs/2022-10-27T20_04_55_053Z-debug-0.log
```

**Comment by Lutymane** [comment]
Current workaround I found is to use [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) in package.json:

```
"overrides": {
      "blake3-wasm": "^3.0.0",
      "@c4312/blake3-internal": "^3.0.0"
    }
```

There are alternatives for other package managers

**Comment by mikeal** [comment]
surprised this still hasn't been fixed.

is this project still being maintained or do i need to fork it?

**Comment by vans163** [comment]
> surprised this still hasn't been fixed.
> 
> is this project still being maintained or do i need to fork it?

I used this package instead, https://www.npmjs.com/package/hash-wasm

**Comment by leonbakadorov** [comment]
> surprised this still hasn't been fixed.
> 
> is this project still being maintained or do i need to fork it?

Yes, you need to fork it. And make sure it works fine.

**Comment by TamaraFinogina** [comment]
Same error, but the workaround works
